name: "Github Workflow"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v3"

      - name: "Set uo Nodejs"
        uses: "actions/setup-node@v3"

      - name: "Install dependencies"
        run: "npm install"

      - name: Ensure Jest is Executable
        run: chmod +x node_modules/.bin/jest
        
      - name: "Run tests"
        run: "npm test"